name: matule
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.3.0
  flutter_svg: ^2.2.3
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.4
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4

  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2

  ui_kit:
    path: ../packages/ui_kit

  api:
    path: ../packages/api

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.2

  freezed: ^3.2.3


flutter:
  uses-material-design: true